### ISSUE TITLE
Issue during admin account password update

### ISSUE THREAD

**Issue by BRUCH05** [borgia-app/Borgia-docs#10]
Hello

I've created this new issue for this case.

(borgiaenv) ***@***.***:/borgia-app/Borgia/borgia#

(borgiaenv) ***@***.***:/borgia-app/Borgia/borgia# python3 manage.py shell

Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

(InteractiveConsole)
>> from users.models import User
>> u = User.objects.get(pk=2)
Traceback (most recent call last):

  File "<console>", line 1, in <module>

  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/manager.py", line 82, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 397, in get

    raise self.model.DoesNotExist(

users.models.User.DoesNotExist: User matching query does not exist.
>>
Thx

Christophe

**Comment by maellacour** [comment]
Based on the limited data provided, it's challenging to fully understand the issue without more context.
However, it appears that the database migration may not have been applied, or you forgot to import the User model.

**Comment by BRUCH05** [comment]
Hello,

Please found the detail below of the database migration.

Thx for your help
Christophe

gestion@test:~$ sudo bash
[sudo] password for gestion:
root@test:/home/gestion# cd /borgia-app/Borgia/borgia
root@test:/borgia-app/Borgia/borgia# source /borgia-app/borgiaenv/bin/activate
(borgiaenv) root@test:/borgia-app/Borgia/borgia# python3 manage.py makemigrations configurations users shops finances events modules sales stocks
python3 manage.py migrate
python3 manage.py loaddata initial
python3 manage.py collectstatic --clear
No changes detected in apps 'stocks', 'events', 'users', 'shops', 'sales', 'configurations', 'finances', 'modules'
Operations to perform:
  Apply all migrations: auth, configurations, contenttypes, events, finances, modules, sales, sessions, shops, static_precompiler, stocks, users
Running migrations:
  No migrations to apply.
Installed 20 object(s) from 2 fixture(s)

You have requested to collect static files at the destination
location as specified in your settings:

    /borgia-app/Borgia/borgia/static/static_root

This will DELETE ALL FILES in this location!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Deleting 'css/font-awesome.css'
Deleting 'css/font-awesome.min.css'
Deleting 'css/fullcalendar.min.css'
Deleting 'img/money.png'
Deleting 'img/group.png'
Deleting 'img/borgia-logo-dark.png'
Deleting 'img/shopping.png'
Deleting 'img/tap.svg'
Deleting 'img/house-outline.svg'
Deleting 'img/token.png'
Deleting 'img/vice_ceo.png'
Deleting 'img/price.png'
Deleting 'img/borgia-logo-light.png'
Deleting 'img/shop.png'
Deleting 'img/lydia.png'
Deleting 'img/lydia_logo.png'
Deleting 'img/history.svg'
Deleting 'img/transfer.svg'
Deleting 'img/store.svg'
Deleting 'img/warning.png'
Deleting 'img/borgia-logo-birse.png'
Deleting 'img/thief.svg'
Deleting 'img/event-calendar-symbol.svg'
Deleting 'img/pexels-photo-27892.jpg'
Deleting 'img/ceo.png'
Deleting 'img/user.png'
Deleting 'img/events.png'
Deleting 'img/coffre.png'
Deleting 'img/settings.png'
Deleting 'img/transfer.png'
Deleting 'img/lazy.svg'
Deleting 'img/keg.png'
Deleting 'img/food.png'
Deleting 'img/favicons/browserconfig.xml'
Deleting 'img/favicons/android-chrome-512x512.png'
Deleting 'img/favicons/safari-pinned-tab.svg'
Deleting 'img/favicons/favicon.ico'
Deleting 'img/favicons/android-chrome-192x192.png'
Deleting 'img/favicons/apple-touch-icon.png'
Deleting 'img/favicons/mstile-150x150.png'
Deleting 'img/favicons/site.webmanifest'
Deleting 'img/favicons/favicon-32x32.png'
Deleting 'img/favicons/favicon-16x16.png'
Deleting 'COMPILED/less/_bootstrap-dark.css'
Deleting 'COMPILED/less/_bootstrap-light.css'
Deleting 'COMPILED/less/_bootstrap-birse.css'
Deleting 'scss/font-awesome.scss'
Deleting 'scss/_core.scss'
Deleting 'scss/_fixed-width.scss'
Deleting 'scss/_larger.scss'
Deleting 'scss/_list.scss'
Deleting 'scss/_animated.scss'
Deleting 'scss/_rotated-flipped.scss'
Deleting 'scss/_mixins.scss'
Deleting 'scss/_path.scss'
Deleting 'scss/_bordered-pulled.scss'
Deleting 'scss/_stacked.scss'
Deleting 'scss/_variables.scss'
Deleting 'scss/_icons.scss'
Deleting 'less/_bootstrap-birse.less'
Deleting 'less/variables-dark.less'
Deleting 'less/variables-light.less'
Deleting 'less/_bootstrap-light.less'
Deleting 'less/variables-birse.less'
Deleting 'less/main.less'
Deleting 'less/_bootstrap-dark.less'
Deleting 'less/less/normalize.less'
Deleting 'less/less/mixins.less'
Deleting 'less/less/utilities.less'
Deleting 'less/less/type.less'
Deleting 'less/less/alerts.less'
Deleting 'less/less/forms.less'
Deleting 'less/less/pagination.less'
Deleting 'less/less/progress-bars.less'
Deleting 'less/less/labels.less'
Deleting 'less/less/pager.less'
Deleting 'less/less/jumbotron.less'
Deleting 'less/less/badges.less'
Deleting 'less/less/input-groups.less'
Deleting 'less/less/tables.less'
Deleting 'less/less/buttons.less'
Deleting 'less/less/modals.less'
Deleting 'less/less/theme.less'
Deleting 'less/less/grid.less'
Deleting 'less/less/carousel.less'
Deleting 'less/less/close.less'
Deleting 'less/less/navbar.less'
Deleting 'less/less/component-animations.less'
Deleting 'less/less/list-group.less'
Deleting 'less/less/dropdowns.less'
Deleting 'less/less/breadcrumbs.less'
Deleting 'less/less/button-groups.less'
Deleting 'less/less/code.less'
Deleting 'less/less/responsive-embed.less'
Deleting 'less/less/thumbnails.less'
Deleting 'less/less/navs.less'
Deleting 'less/less/wells.less'
Deleting 'less/less/popovers.less'
Deleting 'less/less/responsive-utilities.less'
Deleting 'less/less/glyphicons.less'
Deleting 'less/less/scaffolding.less'
Deleting 'less/less/tooltip.less'
Deleting 'less/less/panels.less'
Deleting 'less/less/print.less'
Deleting 'less/less/media.less'
Deleting 'less/less/mixins/resize.less'
Deleting 'less/less/mixins/responsive-visibility.less'
Deleting 'less/less/mixins/nav-vertical-align.less'
Deleting 'less/less/mixins/alerts.less'
Deleting 'less/less/mixins/forms.less'
Deleting 'less/less/mixins/pagination.less'
Deleting 'less/less/mixins/image.less'
Deleting 'less/less/mixins/labels.less'
Deleting 'less/less/mixins/progress-bar.less'
Deleting 'less/less/mixins/reset-filter.less'
Deleting 'less/less/mixins/nav-divider.less'
Deleting 'less/less/mixins/grid-framework.less'
Deleting 'less/less/mixins/buttons.less'
Deleting 'less/less/mixins/vendor-prefixes.less'
Deleting 'less/less/mixins/opacity.less'
Deleting 'less/less/mixins/border-radius.less'
Deleting 'less/less/mixins/grid.less'
Deleting 'less/less/mixins/clearfix.less'
Deleting 'less/less/mixins/text-emphasis.less'
Deleting 'less/less/mixins/center-block.less'
Deleting 'less/less/mixins/list-group.less'
Deleting 'less/less/mixins/background-variant.less'
Deleting 'less/less/mixins/text-overflow.less'
Deleting 'less/less/mixins/reset-text.less'
Deleting 'less/less/mixins/gradients.less'
Deleting 'less/less/mixins/tab-focus.less'
Deleting 'less/less/mixins/table-row.less'
Deleting 'less/less/mixins/hide-text.less'
Deleting 'less/less/mixins/panels.less'
Deleting 'less/less/mixins/size.less'
Deleting 'js/fullcalendar-locale-all.js'
Deleting 'js/moment.min.js'
Deleting 'js/widgets.js'
Deleting 'js/modernizr.custom.js'
Deleting 'js/fullcalendar.min.js'
Deleting 'js/classie.js'
Deleting 'js/mlpushmenu.js'
Deleting 'js/skel-layers.min.js'
Deleting 'js/local.js'
Deleting 'js/skel.min.js'
Deleting 'js/html5shiv.js'
Deleting 'js/init.js'
Deleting 'js/finances/shared_event_create.js'
Deleting 'js/finances/sharedevent_finish.js'
Deleting 'bootstrap-colorpicker-master/css/bootstrap-colorpicker.min.css.map'
Deleting 'bootstrap-colorpicker-master/css/bootstrap-colorpicker.css.map'
Deleting 'bootstrap-colorpicker-master/css/bootstrap-colorpicker.min.css'
Deleting 'bootstrap-colorpicker-master/css/bootstrap-colorpicker.css'
Deleting 'bootstrap-colorpicker-master/img/bootstrap-colorpicker/hue-horizontal.png'
Deleting 'bootstrap-colorpicker-master/img/bootstrap-colorpicker/alpha.png'
Deleting 'bootstrap-colorpicker-master/img/bootstrap-colorpicker/alpha-horizontal.png'
Deleting 'bootstrap-colorpicker-master/img/bootstrap-colorpicker/hue.png'
Deleting 'bootstrap-colorpicker-master/img/bootstrap-colorpicker/saturation.png'
Deleting 'bootstrap-colorpicker-master/js/bootstrap-colorpicker.js'
Deleting 'bootstrap-colorpicker-master/js/bootstrap-colorpicker.min.js'
Deleting 'Lydia_assets/LYDIASDK.js'
Deleting 'Lydia_assets/readme.txt'
Deleting 'Lydia_assets/sample.html'
Deleting 'fonts/glyphicons-halflings-regular.woff'
Deleting 'fonts/glyphicons-halflings-regular.svg'
Deleting 'fonts/FontAwesome.otf'
Deleting 'fonts/glyphicons-halflings-regular.woff2'
Deleting 'fonts/fontawesome-webfont.woff'
Deleting 'fonts/glyphicons-halflings-regular.eot'
Deleting 'fonts/fontawesome-webfont.svg'
Deleting 'fonts/fontawesome-webfont.eot'
Deleting 'fonts/fontawesome-webfont.woff2'
Deleting 'fonts/glyphicons-halflings-regular.ttf'
Deleting 'fonts/fontawesome-webfont.ttf'

174 static files copied to '/borgia-app/Borgia/borgia/static/static_root'.
(borgiaenv) root@test:/borgia-app/Borgia/borgia# python3 manage.py shell
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from users.models import User
>>> u = User.objects.get(pk=2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 397, in get
    raise self.model.DoesNotExist(
users.models.User.DoesNotExist: User matching query does not exist.
>>>

**Comment by BRUCH05** [comment]
Hello,

Do you have any idea following my previous post ?

Thx by advance
Christophe

**Comment by maellacour** [comment]
Not really, are you sure the user exists ?

**Comment by BRUCH05** [comment]
Hello,

1/ Please found the select of users table. There is only one user with id =1

borgia=# \d users_user;
 id              | integer                  |           | not null | nextval('users_user_id_seq'::regclass)
 password        | character varying(128)   |           | not null |
 last_login      | timestamp with time zone |           |          |
 is_superuser    | boolean                  |           | not null |
 username        | character varying(150)   |           | not null |
 first_name      | character varying(30)    |           | not null |
 last_name       | character varying(150)   |           | not null |
 email           | character varying(254)   |           | not null |
 is_staff        | boolean                  |           | not null |
 is_active       | boolean                  |           | not null |
 date_joined     | timestamp with time zone |           | not null |
 surname         | character varying(255)   |           |          |
 family          | character varying(255)   |           |          |
 balance         | numeric(9,2)             |           | not null |
 virtual_balance | numeric(9,2)             |           | not null |
 year            | integer                  |           |          |
 campus          | character varying(3)     |           |          |
 phone           | character varying(255)   |           |          |
 avatar          | character varying(100)   |           |          |
 theme           | character varying(15)    |           |          |
 jwt_iat         | timestamp with time zone |           | not null |

borgia=# select id, username, first_name, last_name from users_user;
  1 | AE_ENSAM | AE         | ENSAM

2/ The same command for changing user password with id=1 does not work. (pk=1)

(borgiaenv) root@test:/borgia-app/Borgia/borgia# python3 manage.py shell
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from users.models import User
>>> u = User.objects.get(pk=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/query.py", line 63, in __iter__
    for row in compiler.results_iter(results):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1466, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1466, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC
>>>

New idea ?
Thx
Christophe

**Comment by BRUCH05** [comment]
Hello,

The intial fixture dataload seems to be ko. Only the user with pk=1 is loaded.
The user with pk=2 is not defined like other user and it seems to be the Administrateur ...
I've duplicated President to Administration with pk=2 and despite this only pk=1 is created :-(
I think this is an issue with django framework, I continue to investigate.

Thx for you help,  if you have an idea :-)
Christophe

root@test:/borgia-app/Borgia/borgia# source /borgia-app/borgiaenv/bin/activate
(borgiaenv) root@test:/borgia-app/Borgia/borgia# python3 manage.py loaddata initial
Installed 20 object(s) from 2 fixture(s)
(borgiaenv) root@test:/borgia-app/Borgia/borgia# su - postgres
postgres@test:~$ psql
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1))
Type "help" for help.

postgres=# \c borgia
You are now connected to database "borgia" as user "postgres".
borgia=# select id, username, first_name, last_name from users_user;
 id | username | first_name | last_name
----+----------+------------+-----------
  1 | AE_ENSAM | AE         | ENSAM
(1 row)

*********************************************************************************************

(borgiaenv) root@test:/borgia-app/Borgia/borgia# cat ./users/fixtures/initial.json
[
    {
        "model": "auth.group",
        "pk": 1,
        "fields": {
        "name": "members",
        "permissions": [
            ["use_selfsalemodule", "modules", "selfsalemodule"],
            ["add_transfert", "finances", "transfert"],

            ["add_event", "events", "event"],
            ["view_event", "events", "event"],
            ["view_user", "users", "user"]
        ]
        }
    },
    {
        "model": "auth.group",
        "pk": 2,
        "fields": {
        "name": "externals",
        "permissions": []
    }
    },
    {
        "model": "auth.group",
        "pk": 3,
        "fields": {
        "name": "presidents",
        "permissions": [
            ["manage_members_group", "users", "user"],
            ["manage_treasurers_group", "users", "user"],
            ["manage_vice_presidents_group", "users", "user"],
            ["manage_presidents_group", "users", "user"],

            ["add_user", "users", "user"],
            ["change_user", "users", "user"],
            ["delete_user", "users", "user"],
            ["view_user", "users", "user"],
            ["advanced_view_user", "users", "user"],

            ["add_shop", "shops", "shop"],
            ["change_shop", "shops", "shop"],
            ["delete_shop", "shops", "shop"],
            ["view_shop", "shops", "shop"],
            ["add_product", "shops", "product"],
            ["change_product", "shops", "product"],
            ["delete_product", "shops", "product"],
            ["view_product", "shops", "product"],
            ["change_price_product", "shops", "product"],
            ["view_stockentry", "stocks", "stockentry"],

            ["change_configuration", "configurations", "configuration"],
            ["view_configuration", "configurations", "configuration"],

            ["add_sale", "sales", "sale"],
            ["view_sale", "sales", "sale"],
            ["add_recharging", "finances", "recharging"],
            ["view_recharging", "finances", "recharging"],
            ["add_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["view_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["add_transfert", "finances", "transfert"],
            ["view_transfert", "finances", "transfert"],

            ["add_event", "events", "event"],
            ["view_event", "events", "event"],
            ["change_event", "events", "event"],
            ["proceed_payment_event", "events", "event"]
        ]
        }
    },
    {
        "model": "auth.group",
        "pk": 4,
        "fields": {
        "name": "vice_presidents",
        "permissions": [
            ["add_user", "users", "user"],
            ["change_user", "users", "user"],
            ["delete_user", "users", "user"],
            ["view_user", "users", "user"],
            ["advanced_view_user", "users", "user"],

            ["add_shop", "shops", "shop"],
            ["change_shop", "shops", "shop"],
            ["delete_shop", "shops", "shop"],
            ["view_shop", "shops", "shop"],
            ["add_product", "shops", "product"],
            ["change_product", "shops", "product"],
            ["delete_product", "shops", "product"],
            ["view_product", "shops", "product"],
            ["change_price_product", "shops", "product"],
            ["view_stockentry", "stocks", "stockentry"],

            ["change_configuration", "configurations", "configuration"],
            ["view_configuration", "configurations", "configuration"],

            ["add_sale", "sales", "sale"],
            ["view_sale", "sales", "sale"],
            ["add_recharging", "finances", "recharging"],
            ["view_recharging", "finances", "recharging"],
            ["add_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["view_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["add_transfert", "finances", "transfert"],
            ["view_transfert", "finances", "transfert"],

            ["add_event", "events", "event"],
            ["view_event", "events", "event"],
            ["change_event", "events", "event"],
            ["proceed_payment_event", "events", "event"]
        ]
        }
    },
    {
        "model": "auth.group",
        "pk": 5,
        "fields": {
        "name": "treasurers",
        "permissions": [
            ["add_user", "users", "user"],
            ["change_user", "users", "user"],
            ["delete_user", "users", "user"],
            ["view_user", "users", "user"],
            ["advanced_view_user", "users", "user"],

            ["add_shop", "shops", "shop"],
            ["change_shop", "shops", "shop"],
            ["delete_shop", "shops", "shop"],
            ["view_shop", "shops", "shop"],
            ["add_product", "shops", "product"],
            ["change_product", "shops", "product"],
            ["delete_product", "shops", "product"],
            ["view_product", "shops", "product"],
            ["change_price_product", "shops", "product"],
            ["view_stockentry", "stocks", "stockentry"],

            ["change_configuration", "configurations", "configuration"],
            ["view_configuration", "configurations", "configuration"],

            ["add_sale", "sales", "sale"],
            ["view_sale", "sales", "sale"],
            ["add_recharging", "finances", "recharging"],
            ["view_recharging", "finances", "recharging"],
            ["add_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["view_exceptionnalmovement", "finances", "exceptionnalmovement"],
            ["add_transfert", "finances", "transfert"],

            ["add_event", "events", "event"],
            ["view_event", "events", "event"],
            ["change_event", "events", "event"],
            ["proceed_payment_event", "events", "event"]
        ]
        }
    },
    {
        "model": "users.user",
        "pk": 1,
        "fields": {
        "is_superuser": false,
        "username": "AE_ENSAM",
        "first_name": "AE",
        "last_name": "ENSAM",
        "email": "",
        "is_staff": false,
        "is_active": true,
        "date_joined": "2016-02-15T13:32:56.781Z",
        "surname": null,
        "family": null,
        "balance": 0.0,
        "year": null,
        "campus": null,
        "phone": null,
        "jwt_iat": "2016-02-15T13:32:56.781Z",
        "groups": [1],
        "user_permissions": []
        }
    }
]

**Comment by maellacour** [comment]
Can you please fix the format of your answer ? it is really hard to read

**Comment by BRUCH05** [comment]
Hello

In one word, only the user with id=1 (pk=1) is created with initial.json despite multiple users defined.
If you are ok, I can open a ssh access for a quick diag.


Thx by advance
Regards
Christophe

**Comment by AlexandrePalo** [comment]
Hi, 
Sorry I'm late in this :)

Can you redo the full dev installation guide, then go in the shell and do the following :
```
from users.models import User
for u in User.objects.all():
    u, u.pk
```
(and hit enter)

This is definitively an issue with the way the initial data is added. I've redone the guide this morning and everything works for me so far. You should have `(<User: AE ENSAM>, 1)`.
Just to be sure, can you please check your Django version ? `python manage.py --version`

**Comment by BRUCH05** [comment]
Hello,

At date, I've performed only the Prod installation.  I've check the python command without success.
So I will perform a Dev installation and check it.  (with new ubuntu VM)

Thx for your help
Christophe

(borgiaenv) root@test:/borgia-app/Borgia/borgia# python3 manage.py shell
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from users.models import User
>>> for u in User.objects.all():
...     u, u.pk
...
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/quer                                                                                                                                                                             y.py", line 268, in __iter__
    self._fetch_all()
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/quer                                                                                                                                                                             y.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/quer                                                                                                                                                                             y.py", line 63, in __iter__
    for row in compiler.results_iter(results):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/sql/                                                                                                                                                                             compiler.py", line 1466, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/models/sql/                                                                                                                                                                             compiler.py", line 1466, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/utils.py",                                                                                                                                                                              line 96, in inner
    return func(*args, **kwargs)
  File "/borgia-app/borgiaenv/lib/python3.10/site-packages/django/db/backends/po                                                                                                                                                                             stgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC
>>>
